---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: user-namespaces
spec:
  generators:
  - matrix:
      generators:
      - git:
          files:
          - path: clusters/vllm.enablement.jharmison.dev/values/user-namespaces/values.yaml
          repoURL: git@github.com:jharmison-redhat/openshift-setup.git
          revision: HEAD
      - list:
          elementsYaml: '{{- range $name := .users }}

            - name: {{ $name }}

            {{- end }}'
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  template:
    metadata:
      name: user-namespace-{{ .name }}
    spec:
      destination:
        name: in-cluster
        namespace: default
      project: default
      source:
        helm:
          valuesObject:
            name: '{{ .name }}'
            namespaceAdmins:
            - '{{ .name }}'
        path: charts/namespace
        repoURL: git@github.com:jharmison-redhat/openshift-setup.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
