roleBindings:
  - name: tenant-admin
    namespace: evalhub-tenant
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: admin
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: developer
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: wcaban
  - name: rhoai-view
    namespace: redhat-ods-applications
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: view
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: developer
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: wcaban

clusterRoleBindings:
  - name: evalhub-mlflow-access
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: trustyai-service-operator-evalhub-mlflow-access
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: developer
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: wcaban
  - name: evalhub-mlflow-jobs-access
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: trustyai-service-operator-evalhub-mlflow-jobs-access
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: developer
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: wcaban
  - name: evalhub-collections-access
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: trustyai-service-operator-evalhub-collections-access
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: developer
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: wcaban
  - name: evalhub-providers-access
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: trustyai-service-operator-evalhub-providers-access
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: developer
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: wcaban
  - name: lmeval-user
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: trustyai-service-operator-lmeval-user-role
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: developer
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: wcaban
  - name: mlflow-view
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: mlflow-operator-mlflow-view
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: developer
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: wcaban
