global:
  cluster:
    name: cluster
    baseDomain: example.com
  toolsImage: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest

keycloak:
  name: keycloak
  realms:
    sso:
      clients:
        ocp-idp:
          secret: abcdefghijkl
      roles:
        user:
          description: Default user role
      admin:
        username: admin
      generated:
        count: 5

removeKubeAdmin: true

cloudnative-pg:
  enabled: true
  clusters:
    - name: keycloak-postgres
