---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kueue-operator
spec:
  destination:
    name: in-cluster
    namespace: openshift-kueue-operator
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/gpuaas.internal.rhai-tmm.dev/cluster.yaml
    path: charts/kueue-operator
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
        openshift.io/cluster-monitoring: 'true'
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
      limit: 10
    syncOptions:
    - CreateNamespace=true
