gateways:
  default-gateway: null
  openshift-ai-inference:
    gatewayClassName: openshift-default
    listeners:
      https:
        hostname: "inference.{{ .Values.global.cluster.name }}-gw.{{ .Values.global.cluster.baseDomain }}"
        port: 443
        protocol: HTTPS
        tls:
          mode: Terminate
          certificateRefs:
            - name: inference-gateway-tls
        certificate:
          create: true
