---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: openshift-ai
spec:
  destination:
    name: in-cluster
    namespace: redhat-ods-operator
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/commons.support.rhai-tmm.dev/cluster.yaml
      - ../../clusters/commons.support.rhai-tmm.dev/values/openshift-ai/values.yaml
    path: charts/openshift-ai
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
      limit: 10
    syncOptions:
    - CreateNamespace=true
