{{- $needsToken := false }}
{{- if and .Values.huggingface.token (hasPrefix "hf://" .Values.model.uri) }}
{{- if not .Values.model.pvc.preload }}
{{- $needsToken = true }}
{{- end }}
{{- end }}
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    openshift.io/display-name: {{ include "llminferenceservice.displayname" . }}
    {{- with .Values.modelType }}
    opendatahub.io/model-type: {{ quote . }}
    {{- end }}
    {{- with .Values.genaiAsset }}
    {{- if and .useCase .enabled }}
    opendatahub.io/genai-use-case: {{ quote .useCase }}
    {{- end }}
    {{- end }}
    {{- if and .Values.enableAuth (not .Values.maas.enabled) }}
    security.opendatahub.io/enable-auth: "true"
    {{- else if not .Values.maas.enabled }}
    security.opendatahub.io/enable-auth: "false"
    {{- end }}
    {{- with .Values.hardwareProfile }}
    {{- if .enabled }}
    opendatahub.io/hardware-profile-name: {{ .name }}
    opendatahub.io/hardware-profile-namespace: {{ .namespace }}
    {{- end }}
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "llminferenceservice.labels" $ | nindent 4 }}
    opendatahub.io/dashboard: "true"
    {{- if or .Values.genaiAsset.enabled .Values.maas.enabled }}
    opendatahub.io/genai-asset: "true"
    {{- end }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "llminferenceservice.name" . }}
spec:
  model:
    name: {{ include "llminferenceservice.name" . }}
    {{- if .Values.model.uri }}
    {{- if .Values.model.pvc.preload }}
    uri: pvc://{{ include "llminferenceservice.fullname" . }}-model
    {{- else }}
    uri: {{ .Values.model.uri }}
    {{- end }}
    {{- end }}
  {{- if and .Values.replicas (not .Values.autoscaling.enabled) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- with .Values.autoscaling }}
  {{- if .enabled }}
  scaling:
    minReplicas: {{ .minReplicas }}
    maxReplicas: {{ .maxReplicas }}
    wva:
      {{- toYaml .wva | nindent 6 }}
  {{- end }}
  {{- end }}
  router:
    {{- if .Values.router.gateway }}
    gateway:
      {{- toYaml . | nindent 6 }}
    {{- else }}
    gateway:
      refs:
        {{- if .Values.maas.enabled }}
        - name: maas-default-gateway
        {{- else }}
        - name: openshift-ai-inference
        {{- end }}
          namespace: openshift-ingress
    {{- end }}
    {{- if .Values.router.createRoute }}
    {{- if .Values.router.route }}
    route:
      {{ toYaml .Values.router.route | nindent 6 }}
    {{- else }}
    route: {}
    {{- end }}
    {{- end }}
    {{- if .Values.router.createScheduler }}
    {{- if .Values.router.scheduler }}
    scheduler:
      {{ toYaml .Values.router.scheduler | nindent 6 }}
    {{- else }}
    scheduler: {}
    {{- end }}
    {{- end }}
  template:
    containers:
      - name: main
        image: {{ include "llminferenceservice.image" . }}
        {{- if or .Values.model.args (or .Values.env $needsToken) }}
        env:
        {{- if $needsToken }}
          - name: HF_HUB_OFFLINE
            value: "0"
        {{- end }}
        {{- with .Values.model.args }}
          - name: VLLM_ADDITIONAL_ARGS
            value: >-
              {{- join " " . | wrap 106 | nindent 14 }}
        {{- end }}
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if $needsToken }}
        envFrom:
            - secretRef:
                name: HF_TOKEN
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
