{{- if .Values.maas.enabled }}
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: {{ include "llminferenceservice.name" . }}
  labels:
    {{- include "llminferenceservice.labels" $ | nindent 4 }}
spec:
  modelRef:
    kind: LLMInferenceService
    name: {{ include "llminferenceservice.name" . }}
{{- end }}
