{{- if .Values.maas.enabled }}
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  name: {{ include "llminferenceservice.fullname" . }}
  namespace: models-as-a-service
  labels:
    {{- include "llminferenceservice.labels" $ | nindent 4 }}
spec:
  modelRefs:
    - name: {{ include "llminferenceservice.fullname" . }}
      namespace: {{ .Release.Namespace }}
  {{- with .Values.maas.subjects }}
  subjects:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
