{{- if .Values.maas.enabled }}
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: {{ include "llminferenceservice.fullname" . }}
  namespace: models-as-a-service
spec:
  modelRef:
    kind: LLMInferenceService
    name: {{ include "llminferenceservice.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
