{{- with .Values.huggingface.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llminferenceservice.fullname" $ }}-token
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    {{- include "llminferenceservice.labels" $ | nindent 4 }}
type: Opaque
data:
  HF_TOKEN: {{ . | b64enc }}
{{- end }}
