{{- with .Values.dataScienceConnection }}
{{- if .create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | default (printf "connection-%s" $.Values.model.name) }}
  annotations:
    opendatahub.io/connection-hidden: "true"
    {{- if $.Values.model.uri }}
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    {{- end }}
  labels:
    {{- include "llminferenceservice.labels" $ | nindent 4 }}
    opendatahub.io/dashboard: "true"
type: Opaque
data:
  {{- with $.Values.model }}
  {{- if and .uri (not .pvc.preload) }}
  URI: {{ .uri | b64enc }}
  {{- else if .uri }}
  URI: {{ printf "pvc://%s-model" (include "llminferenceservice.fullname" $) | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
