global:
  cluster:
    name: cluster
    baseDomain: example.com

gatewayClasses:
  openshift-default: {}

gateways:
  default-gateway:
    gatewayClassName: openshift-default
    listeners:
      https:
        hostname: "*.{{ .Values.global.cluster.name }}-gw.{{ .Values.global.cluster.baseDomain }}"
        port: 443
        protocol: HTTPS
        tls:
          mode: Terminate
          certificateRefs:
            - name: default-gateway-tls
        certificate:
          create: true
