nfd:
  channel: stable
  image: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9@sha256:b0f786e21798c27905c6fdf189bd91cae1f5ddd58ad101a28dbb8b5de92069ce
  configData:
    core:
      sleepInterval: 60s
    sources:
      pci:
        deviceClassWhitelist:
          - "0200"
          - "03"
          - "12"
        deviceLabelFields:
          - "vendor"

gpuOperator:
  channel: v25.3
  timeSlices: 1
  policy:
    operator:
      defaultRuntime: crio
      use_ocp_driver_toolkit: true
      initContainer: {}
    sandboxWorkloads:
      enabled: false
      defaultWorkload: container
    driver:
      enabled: true
      useNvidiaDriverCRD: false
      useOpenKernelModules: false
      upgradePolicy:
        autoUpgrade: true
        drain:
          deleteEmptyDir: false
          enable: false
          force: false
          timeoutSeconds: 300
        maxParallelUpgrades: 1
        maxUnavailable: 25%
        podDeletion:
          deleteEmptyDir: false
          force: false
          timeoutSeconds: 300
        waitForCompletion:
          timeoutSeconds: 0
      repoConfig:
        configMapName: ""
      certConfig:
        name: ""
      licensingConfig:
        nlsEnabled: true
        configMapName: ""
      virtualTopology:
        config: ""
      kernelModuleConfig:
        name: ""
    dcgmExporter:
      enabled: true
      config:
        name: ""
      serviceMonitor:
        enabled: true
    dcgm:
      enabled: true
    daemonsets:
      updateStrategy: RollingUpdate
      rollingUpdate:
        maxUnavailable: "1"
      tolerations:
        - effect: NoSchedule
          operator: Exists
          key: nvidia.com/gpu
    devicePlugin:
      enabled: true
      config:
        name: "{{ if gt (int .Values.gpuOperator.timeSlices) 1 }}device-plugin-config{{ end }}"
        default: ""
      mps:
        root: "/run/nvidia/mps"
    gfd:
      enabled: true
    migManager:
      enabled: true
    nodeStatusExporter:
      enabled: true
    mig:
      strategy: single
    toolkit:
      enabled: true
    validator:
      plugin:
        env:
          - name: WITH_WORKLOAD
            value: "false"
    vgpuManager:
      enabled: false
    vgpuDeviceManager:
      enabled: true
    sandboxDevicePlugin:
      enabled: true
    vfioManager:
      enabled: true
    gds:
      enabled: false
    gdrcopy:
      enabled: false
