---
install-operators:
  enabled: true
  operators:
    rhods-operator:
      channel: stable-3.3
      namespace: redhat-ods-operator
      operatorGroup:
        enabled: true

enableUserTelemetry: false

# If set, will override the deployment replica counts
dashboardReplicas: null
operatorReplicas: null

dataScienceCluster:
  create: true
  version: v2
  components:
    aipipelines:
      managementState: Managed
    dashboard:
      managementState: Managed
    feastoperator:
      managementState: Managed
    kserve:
      managementState: Managed
      modelsAsService:
        managementState: Removed
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headed
    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Removed
    llamastackoperator:
      managementState: Managed
    mlflowoperator:
      managementState: Managed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    ray:
      managementState: Managed
    trainer:
      managementState: Managed
    trainingoperator:
      managementState: Managed
    trustyai:
      eval:
        lmeval:
          permitCodeExecution: deny
          permitOnline: deny
      managementState: Managed
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks

dataScienceClusterInitialization:
  monitoring:
    managementState: Managed
    namespace: redhat-ods-monitoring
    metrics:
      storage:
        size: 5Gi
        retention: 1d

# applicationsNamespace: redhat-ods-applications
# monitoring:
#   managementState: Managed
#   namespace: redhat-ods-monitoring
#   metrics: {}
# trustedCABundle:
#   customCABundle: ""
#   managementState: Managed

hardwareProfiles: []

admins: []
userGroups:
  - system:authenticated

dashboardConfig: {}
# disableAcceleratorProfiles: false
# disableBYONImageStream: false
# disableClusterManager: false
# disableCustomServingRuntimes: false
# disableDistributedWorkloads: false
# disableHome: false
# disableISVBadges: false
# disableInfo: false
# disableKServe: false
# disableKServeAuth: false
# disableKServeMetrics: false
# disableModelMesh: true
# disableModelRegistry: false
# disableModelServing: false
# disablePerformanceMetrics: false
# disablePipelines: false
# disableProjectSharing: false
# disableProjects: false
# disableSupport: false
# disableTracking: true
# enablement: true
# tech preview
# disableHardwareProfiles: true
# disableModelCatalog: true
# #disableKueue: true
# #disableLMEval: true
# #disableFineTuning: true

defaultWorkbenchPvcSize: 20Gi
showJupyterInEnabledApplications: true
notebookIdleCulling:
  enabled: true
  timeoutInMinutes: 240
