---
global:
  toolsImage: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
  cluster:
    name: cluster
    baseDomain: example.com

install-rhoai:
  enabled: true
  operators:
    rhods-operator:
      channel: stable-3.4
      namespace: redhat-ods-operator
      operatorGroup:
        enabled: true
#   cluster-observability-operator:
#     channel: stable
#     namespace: openshift-cluster-observability-operator
#     operatorGroup:
#       enabled: true
#   opentelemetry-product:
#     channel: stable
#   openshift-custom-metrics-autoscaler-operator:
#     channel: stable
#     namespace: openshift-keda
#     operatorGroup:
#       enabled: true

rbac:
  create: true
  group: system:authenticated:oauth

mcpServers: {}

gateways:
  maasDefaultGateway:
    # only created if enabled in DSC
    useRoute: false
    certificate:
      create: true
      clusterIssuer: letsencrypt
  openshiftAiInference:
    create: true
    useRoute: false
    certificate:
      create: true
      clusterIssuer: letsencrypt

enableUserTelemetry: false

# If set, will override the deployment replica counts
dashboardReplicas: null
operatorReplicas: null

dataScienceCluster:
  create: true
  version: v2
  components:
    aipipelines:
      managementState: Managed
    dashboard:
      managementState: Managed
    feastoperator:
      managementState: Managed
    kserve:
      managementState: Managed
      modelsAsService:
        managementState: Removed
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headed
    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Removed
    llamastackoperator:
      managementState: Managed
    mlflowoperator:
      managementState: Managed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    ray:
      managementState: Managed
    trainer:
      managementState: Removed
    trainingoperator:
      managementState: Managed
    trustyai:
      eval:
        lmeval:
          permitCodeExecution: deny
          permitOnline: deny
      managementState: Managed
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks

dataScienceClusterInitialization:
  monitoring:
    managementState: Managed
    namespace: redhat-ods-monitoring
    metrics:
      storage:
        size: 5Gi
        retention: 1d

# applicationsNamespace: redhat-ods-applications
# monitoring:
#   managementState: Managed
#   namespace: redhat-ods-monitoring
#   metrics: {}
# trustedCABundle:
#   customCABundle: ""
#   managementState: Managed

hardwareProfiles: {}

# hardwareProfiles:
#   l40s:
#     node:
#       tolerations:
#         - key: nvidia.com/gpu
#           effect: NoSchedule
#           operator: Exists
#     displayName: NVIDIA L40s
#     cpu:
#       min: 2
#       max: 30
#       default: 2
#     memory:
#       min: 2Gi
#       max: 60Gi
#       default: 16Gi
#     gpu:
#       nvidia.com/gpu:
#         max: 4
#         displayName: NVIDIA L40s

admins: []
userGroups:
  - system:authenticated

dashboardConfig: {}
# disableAcceleratorProfiles: false
# disableBYONImageStream: false
# disableClusterManager: false
# disableCustomServingRuntimes: false
# disableDistributedWorkloads: false
# disableHome: false
# disableISVBadges: false
# disableInfo: false
# disableKServe: false
# disableKServeAuth: false
# disableKServeMetrics: false
# disableModelMesh: true
# disableModelRegistry: false
# disableModelServing: false
# disablePerformanceMetrics: false
# disablePipelines: false
# disableProjectSharing: false
# disableProjects: false
# disableSupport: false
# disableTracking: true
# enablement: true
# tech preview
# disableHardwareProfiles: true
# disableModelCatalog: true
# #disableKueue: true
# #disableLMEval: true
# #disableFineTuning: true

defaultWorkbenchPvcSize: 20Gi
showJupyterInEnabledApplications: true
notebookIdleCulling:
  enabled: true
  timeoutInMinutes: 240

postgres-cluster:
  enabled: false
  nameOverride: maas
  namespace: maas-db
  databases:
    - name: maas
      user: maas

mlflow:
  create: true
  spec:
    storage:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    backendStoreUri: "sqlite:////mlflow/mlflow.db"
    artifactsDestination: "file:///mlflow/artifacts"
    serveArtifacts: true
    image:
      imagePullPolicy: IfNotPresent

evalhub:
  create: false
  spec:
    replicas: 1
    database:
      type: sqlite
    env:
      - name: MLFLOW_TRACKING_URI
        value: https://mlflow.redhat-ods-applications.svc.cluster.local:8443
  tenant:
    create: true
    namespace: evalhub-tenant
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: developer
