{{- with .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes.fullname" $ }}-env
  labels:
    {{- include "hermes.labels" $ | nindent 4 }}
data:
  {{- range $k, $v := . }}
  {{ $k }}: {{ toString $v | b64enc }}
  {{- end }}
{{- end }}
{{- if .Values.oauth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes.fullname" . }}-proxy-session
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
data:
  session_secret: {{ .Values.oauth.sessionSecret | default (randAlphaNum 32) | b64enc }}
{{- end }}
