apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes.fullname" . }}
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
  {{- if .Values.oauth.enabled }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "hermes.fullname" . }}-proxy-svc-tls
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $port := .Values.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.port }}
      protocol: {{ $port.protocol | default "TCP" }}
      name: {{ $name }}
    {{- end }}
    {{- if .Values.oauth.enabled }}
    - port: 8443
      targetPort: oauth
      protocol: TCP
      name: oauth
    {{- end }}
  selector:
    {{- include "hermes.selectorLabels" . | nindent 4 }}
