{{- range $clusterQueue := .Values.clusterQueues }}
{{- range $localQueue := .localQueues }}
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name:
    {{- if $localQueue.name }} {{ $localQueue.name }}
    {{- else }} {{ $clusterQueue.name }}{{ with $localQueue.nameSuffix }}-{{ . }}{{ end }}
    {{- end }}
  namespace: {{ $localQueue.namespace }}
  {{- with $localQueue.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterQueue: {{ $clusterQueue.name }}
  {{- with $localQueue.stopPolicy }}
  stopPolicy: {{ quote . }}
  {{- end }}
{{- end }}
{{- end }}
