{{- range .Values.resourceFlavors }}
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: {{ .name }}
{{- if .spec }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- else }}
spec: {}
{{- end }}
{{- end }}
