apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Values.name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  db:
    vendor: postgres
    database: {{ (get .Values "postgres-cluster").name }}
    host: {{ .Release.Name }}-{{ (get .Values "postgres-cluster").nameOverride }}-rw
    usernameSecret:
      name: {{ .Release.Name }}-{{ (get .Values "postgres-cluster").nameOverride }}-app
      key: username
    passwordSecret:
      name: {{ .Release.Name }}-{{ (get .Values "postgres-cluster").nameOverride }}-app
      key: password
  hostname:
    hostname: {{ include "keycloak.hostname" .Values }}
    strict: false
    strictBackchannel: false
  http:
    httpEnabled: False
    tlsSecret: {{ .Values.name }}-internal-tls
  ingress:
    enabled: false
  instances: {{ .Values.instances }}
  transaction:
    xaEnabled: true
  additionalOptions:
    - name: enable-recovery
      value: 'true'
