{{- range $name, $realm := .Values.realms }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  keycloakCRName: {{ $.Values.name }}
  realm:
    id: {{ $name }}
    realm: {{ $name }}
    enabled: true
    sslRequired: external
    registrationAllowed: {{ $realm.registrationAllowed | default false }}
    loginWithEmailAllowed: {{ $realm.loginWithEmailAllowed | default true }}
    duplicateEmailsAllowed: {{ $realm.duplicateEmailsAllowed | default false }}
    resetPasswordAllowed: {{ $realm.resetPasswordAllowed | default false }}
    editUsernameAllowed: {{ $realm.editUsernameAllowed | default false }}
    bruteForceProtected: {{ $realm.bruteForceProtected | default true }}
    accessTokenLifespan: {{ $realm.accessTokenLifespan | default 300 }}
    ssoSessionIdleTimeout: {{ $realm.ssoSessionIdleTimeout | default 1800 }}
    ssoSessionMaxLifespan: {{ $realm.ssoSessionMaxLifespan | default 36000 }}
    offlineSessionIdleTimeout: {{ $realm.offlineSessionIdleTimeout | default 2592000 }}
    clients:
      {{- range $cid, $client := $realm.clients }}
      - clientId: {{ $cid }}
        {{- with $client.name }}
        name: {{ . }}
        {{- end }}
        {{- with $client.description }}
        description: {{ . }}
        {{- end }}
        enabled: {{ $client.enabled | default true }}
        {{- if not $client.publicClient }}
        {{- if $client.clientAuthenticatorType }}
        clientAuthenticatorType: {{ $client.clientAuthenicatorType }}
        {{- else }}
        clientAuthenticatorType: client-secret
        {{- end }}
        {{- end }}
        {{- with $client.secret }}
        secret: {{ . }}
        {{- end }}
        publicClient: {{ $client.publicClient | default false }}
        redirectUris:
          {{- toYaml (default (list "*") $client.redirectUris) | nindent 10 }}
        webOrigins:
          {{- toYaml (default (list "*") $client.webOrigins) | nindent 10 }}
        standardFlowEnabled: {{ $client.standardFlowEnabled | default true }}
        directAccessGrantsEnabled: {{ $client.directAccessGrantsEnabled | default true }}
        serviceAccountsEnabled: {{ $client.serviceAccountsEnabled | default true }}
        frontchannelLogout: {{ $client.frontchannelLogout | default false }}
        protocol: {{ $client.protocol | default "openid-connect" }}
        {{- with $client.attributes }}
        attributes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $client.fullScopeAllowed }}
        fullScopeAllowed: {{ . }}
        {{- end }}
        {{- with $client.defaultClientScopes }}
        defaultClientScopes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $client.optionalClientScopes }}
        optionalClientScopes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- with $realm.clientScopes }}
    clientScopes:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    roles:
      realm:
        - name: admin
          description: Administrator role
        {{- range $rname, $role := $realm.roles }}
        - name: {{ $rname }}
          {{- if $role }}
          {{- toYaml $role | nindent 10 }}
          {{- end }}
        {{- end }}
    users:
      {{- range $i := until (int $realm.generated.count) }}
      {{- $username := printf "%s%s" $realm.generated.prefix (toString (add 1 $i)) }}
      - username: {{ $username }}
        enabled: true
        emailVerified: true
        email: {{ $username }}@demo.redhat.com
        firstName: {{ title $username }}
        lastName: Demo
        credentials:
          - type: password
            value: {{ $realm.generated.password | quote }}
            temporary: false
        realmRoles:
          - user
      {{- end }}
      {{- range $username, $user := $realm.users }}
      - username: {{ $username }}
        enabled: {{ $user.enabled | default "true" }}
        emailVerified: {{ $user.emailVerified | default "true" }}
        email: {{ $user.email | default (printf "%s@demo.redhat.com" $username) }}
        firstName: {{ $user.firstName | default (title $username) }}
        lastName: {{ $user.lastName | default "Demo" }}
        {{- if $user.credentials }}
        credentials:
          {{- toYaml $user.credentials | nindent 10 }}
        {{- else if $user.password }}
        credentials:
          - type: password
            value: {{ $user.password | quote }}
            temporary: false
        {{- end }}
        {{- with $user.realmRoles }}
        realmRoles:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      - username: {{ $realm.admin.username }}
        enabled: true
        emailVerified: true
        email: {{ $realm.admin.username }}@demo.redhat.com
        firstName: {{ title $realm.admin.username }}
        lastName: Demo
        credentials:
          - type: password
            value: {{ $realm.admin.password | quote }}
            temporary: false
        realmRoles:
          - admin
          {{- with $realm.admin.realmRoles }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
    groups:
    {{- if $realm.groups }}
      {{- toYaml $realm.groups | nindent 6 }}
    {{- else if $realm.groupsFromRoles }}
      - name: admins
      {{- range $rname, $role := $realm.roles }}
      - name: {{ $rname }}
      {{- end }}
    {{- end }}
    {{- with $realm.defaultRoles }}
    defaultRoles:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
