---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: openshift-servicemesh
spec:
  destination:
    name: in-cluster
    namespace: openshift-operators
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/cluster2.demo.jharmison.dev/cluster.yaml
    path: charts/openshift-servicemesh
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
      limit: 10
