{{- range .Values.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name }}
{{- with .rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
