{{- range .Values.roleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
roleRef:
  {{- toYaml .roleRef | nindent 2 }}
subjects:
  {{- toYaml .subjects | nindent 2 }}
{{- end }}
