{{- range .Values.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
{{- with .rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
