{{- $ec2credentials := default .Values.ack.credentials .Values.ack.ec2.credentials }}
{{- $efscredentials := default .Values.ack.credentials .Values.ack.efs.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: ack-ec2-user-secrets
  namespace: ack-system
data:
{{- range $k, $v := $ec2credentials }}
  {{ $k }}: {{ b64enc $v }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ack-efs-user-secrets
  namespace: ack-system
data:
{{- range $k, $v := $efscredentials }}
  {{ $k }}: {{ b64enc $v }}
{{- end }}
