---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aws-efs-csi-driver-operator
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  channel: '{{ .Values.channel }}'
  installPlanApproval: Automatic
  name: aws-efs-csi-driver-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
