{{- with .Values.operatorReplicas }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  replicas: {{ . }}
{{- end }}
