{{- if .Values.wvaOverrides }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-variant-autoscaler-saturation-scaling-config
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "8"
data:
{{- range $name, $override := .Values.wvaOverrides }}
  {{ $name }}: |
    {{- toYaml $override | nindent 4 }}
{{- end }}
{{- end }}
