---
clusterRoleBindings:
- name: clusterqueue-viewer
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kueue-clusterqueue-viewer-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: demouser
- name: resourceflavor-viewer
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kueue-resourceflavor-viewer-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: demouser
- name: clusterrole-viewer
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rbac-viewer-cluster
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: demouser
clusterRoles:
- name: rbac-viewer-namespaced
  rules:
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - rolebindings
    - roles
    verbs:
    - get
    - list
    - watch
- name: rbac-viewer-cluster
  rules:
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterroles
    verbs:
    - get
    - list
    - watch
- name: accelerator-profiles-viewer
  rules:
  - apiGroups:
    - dashboard.opendatahub.io
    resources:
    - acceleratorprofiles
    verbs:
    - get
    - list
    - watch
roleBindings:
- name: demouser-edit
  namespace: demo-project
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: demouser
- name: demouser-kueue-user
  namespace: demo-project
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kueue-batch-user-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: demouser
- name: demouser-rbac-viewer
  namespace: demo-project
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rbac-viewer-namespaced
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: demouser
- name: demouser-acceleratorprofile-viewer
  namespace: demo-project
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: accelerator-profiles-viewer
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: demouser
- name: rhoai-users
  namespace: redhat-ods-applications
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: demouser
