---
install-odf:
  enabled: true
  operators:
    odf-operator:
      channel: stable-4.21
      namespace: openshift-storage
      targetNamespaces:
        - openshift-storage
      operatorGroup:
        enabled: true

enableCephTools: true
createStorageSystem: false
storageDeviceSets: []
disks: []
enableConsolePlugin: true
resources: {}
multiCloudGateway: {}
resourceProfile: balanced
