---
displaynameOverride: Granite 3.3 8B Instruct
fullnameOverride: granite33-8b
model:
  extraArgs:
  - --enable-auto-tool-choice
  - --tool-call-parser
  - granite
  - --chat-template
  - /app/data/template/tool_chat_template_granite.jinja
  uri: oci://quay.io/jharmison/models:ibm-granite--granite-3_3-8b-instruct-modelcar
scaling:
  maxReplicas: 3
  minReplicas: 1
  progressDeadline: 45m
  retentionPeriod: 1m
  scaleTarget: 5
