---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kueue-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: Automatic
  name: kueue-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
