apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: rhbk
      type: OpenID
      mappingMethod: claim
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: {{ (index .Values.keycloak.realms.sso.clients "ocp-idp").secret }}
        clientSecret:
          name: openid-client-secret
        extraScopes: []
        issuer: >-
          https://{{ include "keycloak.hostname" .Values.keycloak }}/realms/{{ (first (keys .Values.keycloak.realms)) }}
