apiVersion: v1
kind: Secret
metadata:
  name: openid-client-secret
  namespace: openshift-config
type: Opaque
data:
  clientSecret: {{ (index .Values.keycloak.realms.sso.clients "ocp-idp").secret | b64enc }}
