---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: llama-4-scout
spec:
  destination:
    name: in-cluster
    namespace: models
  project: default
  source:
    helm:
      valueFiles:
        - ../../clusters/nightly.internal.rhai-tmm.dev/cluster.yaml
        - ../../clusters/nightly.internal.rhai-tmm.dev/values/llmisvc/llama-4-scout.yaml
    path: charts/llmisvc
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 60m
      limit: 10
    syncOptions:
      - RespectIgnoreDifferences=true
