---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: rhoai-nightly
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  sources:
    - path: bootstrap/icsp
      repoURL: https://github.com/rh-aiservices-bu/rhoai-nightly.git
      targetRevision: 853a8a7280149a3b9bfda0fc872262b1ed9ef285
    - path: bootstrap/external-secrets
      repoURL: https://github.com/rh-aiservices-bu/rhoai-nightly.git
      targetRevision: 853a8a7280149a3b9bfda0fc872262b1ed9ef285
    - path: components/operators/rhoai-operator
      repoURL: https://github.com/rh-aiservices-bu/rhoai-nightly.git
      targetRevision: 853a8a7280149a3b9bfda0fc872262b1ed9ef285
    - path: components/instances/maas-observability/base
      repoURL: https://github.com/rh-aiservices-bu/rhoai-nightly.git
      targetRevision: 853a8a7280149a3b9bfda0fc872262b1ed9ef285
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
      limit: 10
