---
displaynameOverride: Mistral Small 3.1 24B FP8
fullnameOverride: mistral-small-31
model:
  extraArgs:
  - --enable-auto-tool-choice
  - --tool-call-parser=mistral
  - --chat-template=/app/data/template/tool_chat_template_mistral.jinja
  - --max-model-len=65536
  uri: oci://quay.io/jharmison/models:redhatai--mistral-small-3_1-24b-instruct-2503-fp8-dynamic-modelcar
scaling:
  maxReplicas: 3
  minReplicas: 1
  progressDeadline: 60m
  retentionPeriod: 1m
  scaleTarget: 5
