global:
  toolsImage: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest

install-rhcl:
  enabled: true
  operators:
    rhcl-operator:
      channel: stable
      namespace: kuadrant-system
      ownSubscription: false
      installPlanApproval: Manual
      startingCSV: rhcl-operator.v1.3.4
      operatorGroup:
        enabled: true

kuadrant:
  create: true
  namespace: kuadrant-system
  spec:
    observability:
      enable: true

authorino:
  overwrite: true
  serviceTls: true
  spec:
    listener:
      tls:
        certSecretRef:
          name: authorino-server-cert
        enabled: true
