{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: {{ .Values.cluster.infraID }}-gpu-worker-{{ .Values.azure.region }}
spec:
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: {{ .Values.cluster.infraID }}-gpu-worker-{{ .Values.azure.region }}
{{- end }}
