tags:
  autoscaling: false
  loadBalancing: false
  openshift: true

modelRepository:
  nfs:
    server: fs-0424d3fc71b9bc365.efs.us-east-2.amazonaws.com
    path: /models

deployment:
  strategy:
    type: Recreate
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
