server:
  disableTls: true
  oidc:
    issuer: https://keycloak.apps.nightly.internal.rhai-tmm.dev/realms/sso
    audience: openshell
    roleClaim: realm_access.roles
    adminRole: admin
    userRole: openshell

pkiInitJob:
  enabled: false

podSecurityContext:
  fsGroup: null

securityContext:
  runAsUser: null

grpcRoute:
  enabled: true
  hostnames:
    - openshell.nightly-gw.internal.rhai-tmm.dev
  gateway:
    create: false
    name: default-gateway
    namespace: openshift-ingress
