server:
  disableTls: true

pkiInitJob:
  enabled: false

podSecurityContext:
  fsGroup: null

securityContext:
  runAsUser: null

grpcRoute:
  enabled: true
  hostnames:
    - openshell.nightly-gw.internal.rhai-tmm.dev
  gateway:
    create: false
    name: default-gateway
    namespace: openshift-ingress
