{{- if .Values.exposedWithToken }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kserve-vllm-model.serviceAccountName" . }}
  labels:
    {{- include "kserve-vllm-model.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kserve-vllm-model.serviceAccountName" . }}-view-role
  labels:
    opendatahub.io/dashboard: "true"
    {{- include "kserve-vllm-model.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: ["serving.kserve.io"]
  resources: ["inferenceservices"]
  verbs: ["get"]
  resourceNames: [{{ include "kserve-vllm-model.fullname" . | quote}}]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kserve-vllm-model.serviceAccountName" . }}-view
  labels:
    opendatahub.io/dashboard: "true"
    {{- include "kserve-vllm-model.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
- kind: ServiceAccount
  name: {{ include "kserve-vllm-model.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kserve-vllm-model.serviceAccountName" . }}-view-role
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount.tokenName }}-{{ include "kserve-vllm-model.serviceAccountName" . }}
  labels:
    opendatahub.io/dashboard: "true"
    {{- include "kserve-vllm-model.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    kubernetes.io/service-account.name: {{ include "kserve-vllm-model.serviceAccountName" . }}
    openshift.io/display-name: {{ .Values.serviceAccount.tokenName }}
type: kubernetes.io/service-account-token
{{- end }}
