{{- range $pullsecret := .Values.image.pullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pullsecret.name }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "kserve-vllm-model.dockerconfigjson" (dict "registry" $.Values.image.registry "pullSecret" $pullsecret) | b64enc }}
{{- end }}
