{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "postgres-cluster.fullname" . }}
  {{- with .Values.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "postgres-cluster.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ include "postgres-cluster.certificate.secret.fullname" . }}
  usages:
    - server auth
  dnsNames:
    {{- $ns := .Values.namespace | default .Release.Namespace }}
    {{- range $svc := .Values.services }}
    - {{ include "postgres-cluster.fullname" $ }}-{{ $svc }}
    - {{ include "postgres-cluster.fullname" $ }}-{{ $svc }}.{{ $ns }}
    - {{ include "postgres-cluster.fullname" $ }}-{{ $svc }}.{{ $ns }}.svc
    {{- if $.Values.certificate.clusterDomain }}
    - {{ include "postgres-cluster.fullname" $ }}-{{ $svc }}.{{ $ns }}.svc.{{ $.Values.certificate.clusterDomain }}
    {{- end }}
    {{- end }}
  issuerRef:
    {{- toYaml .Values.certificate.issuerRef | nindent 4 }}
{{- end }}
