{{- range $db := .Values.databases }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ include "postgres-cluster.fullname" $ }}-{{ $db.name }}
  {{- with $.Values.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "postgres-cluster.labels" $ | nindent 4 }}
    {{- with $db.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $db.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  name: {{ $db.name }}
  owner: {{ $db.user | default $db.name }}
  cluster:
    name: {{ include "postgres-cluster.fullname" $ }}
  {{- with $db.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- if $db.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-cluster.fullname" $ }}-{{ $db.user | default $db.name }}-{{ $db.name }}
  {{- with $.Values.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "postgres-cluster.labels" $ | nindent 4 }}
    {{- with $db.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    cnpg.io/reload: "true"
    cnpg.io/userType: app
  {{- with $db.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/basic-auth
data:
  username: {{ $db.user | default $db.name | b64enc }}
  password: {{ $db.password | b64enc }}
{{- end }}
{{- end }}
