{{- if .Values.certificate.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-cluster.certificate.secret.fullname" . }}
  {{- with .Values.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "postgres-cluster.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    cnpg.io/reload: ""
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
