---
providers:
  htpasswd:
    ## You can just put username/password here, they will generate once and never update
    admin: openshift
    developer: openshift
    ## If you put htpasswd in this array, all other fields are ignored
#   htpasswd: |-
#     admin:$2a$10$WFVlLRXkUTKAZNfqM68DSO8trAopkE9.qwJSzoOOcYj25dXyDFTbC
## Alternatively, you can set `htpasswd` to `null` and use github
# github:
#   organizations:
#     - <your GH org name goes here>
#   clientId: <your client ID goes here>
#   clientSecret: <your client secret goes here>
admins:
  - admin

clusterReaders: []
## You can add users to the array here to grant cluster-wide reader privileges,
# which doesn't include reading secrets
#  - developer

mappingMethod: claim

removeKubeAdmin: true

openshiftToolsImage: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:96f217fd794eed50ee2c075d44ec56b7f8cfed4370662df59dc06c70ac2d67c0
