---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crunchydata-postgres-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: in-cluster
    namespace: openshift-operators
  project: default
  source:
    path: charts/crunchydata-postgres-operator
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../clusters/cluster.demo.jharmison.dev/cluster.yaml
        - secrets+age-import:///helm-secrets-private-keys/argo.txt?../../clusters/cluster.demo.jharmison.dev/values/crunchydata-postgres-operator/secrets.enc.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
