---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-33-70b
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    name: in-cluster
    namespace: model-serving
  project: default
  source:
    path: charts/vllm-chart
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - ../../clusters/cluster.demo.jharmison.dev/cluster.yaml
      - ../../clusters/cluster.demo.jharmison.dev/values/llama-33-70b/values.yaml
      - secrets+age-import:///helm-secrets-private-keys/argo.txt?../../clusters/cluster.demo.jharmison.dev/values/llama-33-70b/secrets.enc.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 60m
