---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: mistral-31-24b
spec:
  destination:
    name: in-cluster
    namespace: model-serving
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/cluster.demo.jharmison.dev/cluster.yaml
      - ../../clusters/cluster.demo.jharmison.dev/values/mistral-31-24b-kserve-vllm-model/values.yaml
    path: charts/kserve-vllm-model
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 60m
      limit: 10
