---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    name: in-cluster
    namespace: redhat-ods-operator
  project: default
  source:
    path: charts/openshift-ai
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../clusters/cluster.demo.jharmison.dev/cluster.yaml
        - ../../clusters/cluster.demo.jharmison.dev/values/openshift-ai/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
