---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '6'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: summit-demo
spec:
  destination:
    name: in-cluster
    namespace: llama-serve
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/cluster.demo.jharmison.dev/cluster.yaml
      - secrets+age-import:///helm-secrets-private-keys/argo.txt?../../clusters/cluster.demo.jharmison.dev/values/summit-demo/secrets.enc.yaml
    path: charts/summit-demo
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 60m
      limit: 10
    syncOptions:
    - CreateNamespace=true
