---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: triton-server
spec:
  destination:
    name: in-cluster
    namespace: triton-server
  ignoreDifferences:
  - group: apps
    jsonPointers:
    - /spec/replicas
    kind: Deployment
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/cluster.demo.jharmison.dev/cluster.yaml
      - ../../clusters/cluster.demo.jharmison.dev/values/triton-server/values.yaml
    path: charts/triton-server
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
      limit: 10
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
