nameOverride: ""
fullnameOverride: ""

namespace: ""

image: ""

instances: 2

storage:
  size: 10Gi
  storageClass: gp3-csi

resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 256Mi

walStorage: {}

managed: {}

services:
  # if you change these, make sure you don't specify `services` in the `managed` block
  - rw
  - ro
  - r

certificate:
  enabled: true
  clusterDomain: cluster.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io

backups:
  enabled: true
  schedule: "0 30 1 * * 6" # 1:30 AM on Saturdays
  method: volumeSnapshot
  ownerReference: self
  volumeSnapshot:
    className: csi-aws-vsc

databases: [] # if you specify more than one, make sure you don't specify `roles` in the `managed` block

recovery: {} # if you specify this, instead of databases, the bootstrap will specify recovery from this target
