apiVersion: v1
kind: Secret
metadata:
  name: crm-mcp-server-secrets
type: Opaque
data:
  DB_HOST: {{ "postgresql.llama-serve.svc.cluster.local" | b64enc }}
  DB_NAME: {{ "claimdb" | b64enc }}
  DB_PASSWORD: {{ "claimdb" | b64enc }}
  DB_USER: {{ "claimdb" | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: crm-mcp-server
  name: crm-mcp-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: crm-mcp-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crm-mcp-server
  name: crm-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-mcp-server
  template:
    metadata:
      labels:
        app: crm-mcp-server
    spec:
      containers:
      - args:
        - npx -y supergateway --stdio "node app/index.js" --port 8080
        command:
        - /bin/sh
        - -c
        env:
        - name: NPM_CONFIG_CACHE
          value: /tmp/.npm
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: crm-mcp-server-secrets
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: crm-mcp-server-secrets
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: crm-mcp-server-secrets
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: crm-mcp-server-secrets
        image: quay.io/rh-aiservices-bu/mcp-servers:crm
        imagePullPolicy: Always
        name: crm-mcp-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
