apiVersion: v1
kind: Service
metadata:
  labels:
    app: pdf-mcp-server
  name: pdf-mcp-server
spec:
  ports:
  - port: 8010
    targetPort: 8010
  selector:
    app: pdf-mcp-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pdf-mcp-server
  name: pdf-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-mcp-server
  template:
    metadata:
      labels:
        app: pdf-mcp-server
    spec:
      containers:
      - args:
        - npx -y supergateway --stdio "node build/index.js" --port 8010
        command:
        - /bin/sh
        - -c
        env:
        - name: NPM_CONFIG_CACHE
          value: /tmp/.npm
        image: quay.io/rh-aiservices-bu/mcp-servers:pdf
        imagePullPolicy: Always
        name: pdf-mcp-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
