apiVersion: v1
kind: Service
metadata:
  labels:
    app: upload-mcp-server
  name: upload-mcp-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: upload-mcp-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: upload-mcp-server
  name: upload-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-mcp-server
  template:
    metadata:
      labels:
        app: upload-mcp-server
    spec:
      containers:
      - args:
        - |
          npx -y supergateway --stdio "node dist/index.js" --port 8080
        command:
        - /bin/sh
        - -c
        env:
        - name: NPM_CONFIG_CACHE
          value: /tmp/.npm
        image: quay.io/rh-aiservices-bu/mcp-servers:upload
        imagePullPolicy: Always
        name: upload-mcp-server
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
