---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: rhcl
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/cluster.internal.rhai-tmm.dev/cluster.yaml
    path: charts/rhcl
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
      limit: 10
