{{- with .Values.clusterMonitoringConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.userWorkloadMonitoringConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    {{- toYaml . | nindent 4 }}
{{- end }}
