---
subscriptions:
  agentic:
    groups:
    - name: system:authenticated:oauth
    models:
      gemma-4: null
      llama-4-scout: null
      nemotron-3-nano-30b-a3b-fp8:
        namespace: models
        tokenRateLimits:
        - limit: 50000
          window: 1m
