subscriptions:
  maas-user:
    models:
      abliterated-gemma-4-31b-it:
        namespace: models
        tokenRateLimits:
          - limit: 200000
            window: 1s
      nemotron-3-nano-30b-a3b:
        namespace: models
        tokenRateLimits:
          - limit: 200000
            window: 1s
    groups:
      - name: system:authenticated:oauth
