install-operators:
  enabled: false

dashboardReplicas: 1
operatorReplicas: 1
dataScienceCluster:
  components:
    kserve:
      modelsAsService:
        managementState: Managed

dashboardConfig:
  disableKServeMetrics: false
  disableLMEval: false
  genAiStudio: true
  modelAsService: true
  observabilityDashboard: true

hardwareProfiles:
  l40s:
    node:
      tolerations:
        - key: nvidia.com/gpu
          effect: NoSchedule
          operator: Exists
    displayName: NVIDIA L40s
    cpu:
      min: 2
      max: 40
      default: 2
    memory:
      min: 2Gi
      max: 256Gi
      default: 16Gi
    gpu:
      nvidia.com/gpu:
        max: 4
        displayName: NVIDIA L40s

postgres-cluster:
  enabled: true
