---
baseName: worker-t4
desiredReplicas: 2
instanceType: g4dn.2xlarge
nodeLabels:
  jharmison.dev/gpu-type: t4
  node-role.kubernetes.io/gpu: ''
taints:
- effect: NoSchedule
  key: nvidia.com/gpu
  value: t4
aws:
  az: us-west-2b
