{{- if .Values.kuadrant.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: restart-kuadrant-operator
  namespace: {{ .Values.kuadrant.namespace }}
  labels:
    {{- include "rhcl.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: restart-kuadrant-operator
      restartPolicy: Never
      containers:
        - name: restart-kuadrant-operator
          image: {{ .Values.global.toolsImage }}
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command: ["/app/restart-kuadrant-operator.sh"]
          args: []
          volumeMounts:
            - name: restart-kuadrant-operator-script
              mountPath: /app
      volumes:
        - name: restart-kuadrant-operator-script
          configMap:
            name: restart-kuadrant-operator-script
            defaultMode: 493
{{- end }}
