{{- if .Values.kuadrant.create }}
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: {{ .Values.kuadrant.namespace }}
  labels:
    {{- include "rhcl.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
{{- with .Values.kuadrant.spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
