{{- $operatorNs := (index (index $.Values "install-rhcl").operators "rhcl-operator").namespace | default "openshift-operators" }}
{{- if and .Values.kuadrant.create (not (eq $operatorNs .Values.kuadrant.namespace)) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.kuadrant.namespace }}
  labels:
    {{- include "rhcl.labels" . | nindent 4 }}
{{- end }}
