---
gpuOperator:
  policy:
    driver:
      version: 550.163.01
      image: driver
      repository: nvcr.io/nvidia

nfd:
  image: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9:v4.18
  configData:
    sources:
      custom:
        - name: amd-gpu
          labels:
            feature.node.kubernetes.io/amd-gpu: "true"
          matchAny:
            - matchFeatures:
                - feature: pci.device
                  matchExpressions:
                    vendor: {op: In, value: ["1002"]}
                    device: {op: In, value: [
                      "74a0", # MI300A
                      "74a1", # MI300X
                      "740f", # MI210
                      "7408", # MI250X
                      "740c", # MI250/MI250X
                      "738c", # MI100
                      "738e"  # MI100
                    ]}
