apiVersion: v1
kind: ConfigMap
metadata:
  name: ack-ec2-user-config
data:
  ACK_ENABLE_DEVELOPMENT_LOGGING: {{ .Values.enableDevelopmentLogging | quote }}
  ACK_LOG_LEVEL: {{ .Values.logLevel | quote }}
  ACK_WATCH_NAMESPACE: ""
  AWS_REGION: {{ .Values.aws.region }}
  AWS_ENDPOINT_URL: {{ .Values.awsEndpointURL | quote }}
  ACK_RESOURCE_TAGS: {{ .Values.resourceTags | quote }}
  ENABLE_LEADER_ELECTION: {{ .Values.enableLeaderElection | quote }}
  LEADER_ELECTION_NAMESPACE: ""
  RECONCILE_DEFAULT_MAX_CONCURRENT_SYNCS: {{ .Values.maxConcurrentSyncs | quote }}
  FEATURE_FLAGS: ""
  FEATURE_GATES: ""
