---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: aws-nvidia-gpu-machinesets
spec:
  destination:
    name: in-cluster
    namespace: openshift-machine-api
  ignoreDifferences:
  - group: machine.openshift.io
    jsonPointers:
    - /spec/replicas
    kind: MachineSet
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/rhoai.audrey.jharmison.dev/cluster.yaml
      - ../../clusters/rhoai.audrey.jharmison.dev/values/aws-nvidia-gpu-machinesets/values.yaml
    path: charts/aws-nvidia-gpu-machinesets
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
      limit: 10
    syncOptions:
    - RespectIgnoreDifferences=true
