---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kueue
spec:
  destination:
    name: in-cluster
    namespace: redhat-ods-applications
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/garfield.internal.rhai-tmm.dev/cluster.yaml
      - ../../clusters/garfield.internal.rhai-tmm.dev/values/kueue/values.yaml
    path: charts/kueue
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
      limit: 10
