---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: oauth
spec:
  destination:
    name: in-cluster
    namespace: openshift-config
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/garfield.internal.rhai-tmm.dev/cluster.yaml
      - ../../clusters/garfield.internal.rhai-tmm.dev/values/oauth/values.yaml
      - secrets+age-import:///helm-secrets-private-keys/argo.txt?../../clusters/garfield.internal.rhai-tmm.dev/values/oauth/secrets.enc.yaml
    path: charts/oauth
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    ignoreDifferences:
    - jsonPointers:
      - /data/htpasswd
      kind: Secret
    syncOptions:
    - RespectIgnoreDifferences=true
