---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: rbac-test-namespace
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
      - ../../clusters/garfield.internal.rhai-tmm.dev/cluster.yaml
      - ../../clusters/garfield.internal.rhai-tmm.dev/values/rbac-test-namespace/values.yaml
    path: charts/namespace
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
